
package de.scrummies.scrumService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScrumService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://fuldaai.cloudapp.net/ScrumService.svc?wsdl")
public class ScrumService
    extends Service
{

    private final static URL SCRUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCRUMSERVICE_EXCEPTION;
    private final static QName SCRUMSERVICE_QNAME = new QName("http://tempuri.org/", "ScrumService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fuldaai.cloudapp.net/ScrumService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCRUMSERVICE_WSDL_LOCATION = url;
        SCRUMSERVICE_EXCEPTION = e;
    }

    public ScrumService() {
        super(__getWsdlLocation(), SCRUMSERVICE_QNAME);
    }

    public ScrumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCRUMSERVICE_QNAME, features);
    }

    public ScrumService(URL wsdlLocation) {
        super(wsdlLocation, SCRUMSERVICE_QNAME);
    }

    public ScrumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCRUMSERVICE_QNAME, features);
    }

    public ScrumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScrumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IScrumService
     */
    @WebEndpoint(name = "BasicHttpBinding_IScrumService")
    public IScrumService getBasicHttpBindingIScrumService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IScrumService"), IScrumService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IScrumService
     */
    @WebEndpoint(name = "BasicHttpBinding_IScrumService")
    public IScrumService getBasicHttpBindingIScrumService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IScrumService"), IScrumService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCRUMSERVICE_EXCEPTION!= null) {
            throw SCRUMSERVICE_EXCEPTION;
        }
        return SCRUMSERVICE_WSDL_LOCATION;
    }

}
